apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: gitops-app
spec:
  selector:
    app: gitops-app

  ports:
    - port: 8080
      targetPort: 80

  type: LoadBalancer
